version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: investment
      POSTGRES_USER: investment
      POSTGRES_PASSWORD: investment
    ports:
      - 5432:5432
    volumes:
      - investment-db:/var/lib/postgresql/data

volumes:
  investment-db:
    driver: local
